project:
  type: website
  output-dir: docs

website:
  title: "Coding Initiative @ IITGN"
  sidebar:
    background: secondary
    logo: "https://www.iitgn.ac.in/assets/img/Final_IITGN_Logo_symmetric.svg"
    logo-href: "iitgn.ac.in"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/Pakillo/quarto-course-website-template
        text: GitHub
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: events.qmd
        text: Events
      - href: about.qmd
        text: About

format:
  html:
    theme: morph
    # css: styles.css
    toc: true

execute:
  freeze: auto

