project:
  type: website
  output-dir: docs

website:
  title: "Coding Initiative @ IITGN"
  sidebar:
    background: primary
    logo: "https://www.iitgn.ac.in/assets/img/iitgnlogo-emblem.png"
    logo-href: "iitgn.ac.in"
    pinned: true
    align: center
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: events.qmd
        text: Events
      - href: about.qmd
        text: About

format:
  html:
    theme: morph
    # css: styles.css
    toc: true

execute:
  freeze: auto

